# Generated by Django 3.1.4 on 2020-12-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Like', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Image', models.ImageField(upload_to='productImage')),
                ('NoOfLikes', models.IntegerField(default=0)),
                ('NoOfDislikes', models.IntegerField(default=0)),
                ('NoOfComments', models.IntegerField(default=0)),
                ('LaunchDate', models.DateTimeField(auto_now_add=True)),
                ('AllComments', models.ManyToManyField(to='main.Comments')),
                ('AllLikes', models.ManyToManyField(to='main.Likes')),
            ],
        ),
    ]
