# Generated by Django 3.1.4 on 2020-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201222_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='Like',
            field=models.IntegerField(default=-1),
        ),
    ]
